# Generated by Django 3.0.5 on 2021-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('gameCnt', models.CharField(max_length=20)),
                ('win', models.CharField(max_length=20)),
                ('lose', models.CharField(max_length=20)),
                ('draw', models.CharField(max_length=20)),
            ],
        ),
    ]
