# Generated by Django 3.0.5 on 2021-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleague_Schedule', '0002_auto_20210604_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dataCnt',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
